const fleetRoutes = [
  { id: 'SN-204', customer: 'Northstar Medical', origin: 'Manchester', destination: 'Leeds', driver: 'Amelia Carter', vehicle: 'SN-14', status: 'On route', departure: '09:15', eta: '14:35', temperature: '4.2 C', progress: '72%' },
  { id: 'SN-205', customer: 'Carewell Clinics', origin: 'Liverpool', destination: 'Sheffield', driver: 'Marcus Green', vehicle: 'SN-08', status: 'Loading', departure: '12:00', eta: '16:10', temperature: '3.8 C', progress: '28%' },
  { id: 'SN-206', customer: 'MedEquip UK', origin: 'Birmingham', destination: 'Nottingham', driver: 'Nia Patel', vehicle: 'SN-22', status: 'On route', departure: '10:30', eta: '17:20', temperature: '5.1 C', progress: '54%' },
  { id: 'SN-207', customer: 'Wellbeing Direct', origin: 'Bristol', destination: 'Cardiff', driver: 'Owen Hughes', vehicle: 'SN-05', status: 'Awaiting driver', departure: '15:00', eta: '18:45', temperature: '3.4 C', progress: '0%' },
]

const vehicles = [
  { id: 'SN-14', type: 'Refrigerated van', driver: 'Amelia Carter', temperature: '4.2 C', range: 'Within range', status: 'In transit', mileage: '42,810 mi' },
  { id: 'SN-08', type: 'Refrigerated van', driver: 'Marcus Green', temperature: '3.8 C', range: 'Within range', status: 'Loading', mileage: '38,204 mi' },
  { id: 'SN-22', type: 'Long wheelbase van', driver: 'Nia Patel', temperature: '5.1 C', range: 'Within range', status: 'In transit', mileage: '51,620 mi' },
  { id: 'SN-19', type: 'Refrigerated van', driver: 'Unassigned', temperature: '8.7 C', range: 'Temperature alert', status: 'Parked', mileage: '45,108 mi' },
  { id: 'SN-05', type: 'Refrigerated van', driver: 'Owen Hughes', temperature: '3.4 C', range: 'Within range', status: 'Available', mileage: '29,440 mi' },
]

export const RoutesPage = () => (
  <div class="fleet-dashboard">
    <div class="page-heading"><div><p class="eyebrow">Fleet management</p><h1>Routes</h1><p class="header-copy">Allocate work, follow delivery progress, and respond to route disruption.</p></div><div class="header-actions"><a class="button button-secondary" href="/routes/scan">Scan for routes</a><a class="button button-primary" href="/routes/new">+ Allocate route</a></div></div>
    <section class="panel table-panel"><div class="panel-heading"><div><h2>Today's delivery routes</h2><p class="table-caption">4 routes currently scheduled across the network</p></div><a class="text-link" href="/alerts">View route alerts <span>â†’</span></a></div><div class="fleet-table-wrap"><table class="fleet-table"><thead><tr><th>Route</th><th>Customer</th><th>Driver / vehicle</th><th>Progress</th><th>ETA</th><th>Status</th></tr></thead><tbody>{fleetRoutes.map(route => <tr><td><a href={`/routes/${route.id}`} class="table-id">{route.id}</a><span>{route.origin} <b>â†’</b> {route.destination}</span></td><td>{route.customer}</td><td>{route.driver}<span>{route.vehicle}</span></td><td><div class="table-progress"><span style={`width: ${route.progress}`}></span></div><small>{route.progress}</small></td><td>{route.eta}<span>Departs {route.departure}</span></td><td><span class={`pill ${route.status === 'On route' ? 'pill-green' : route.status === 'Loading' ? 'pill-amber' : 'pill-neutral'}`}>{route.status}</span></td></tr>)}</tbody></table></div></section>
  </div>
  )

export const RouteDetailPage = ({ routeId }: { routeId: string }) => {
  const route = fleetRoutes.find(candidate => candidate.id.toLowerCase() === routeId.toLowerCase()) || fleetRoutes[0]
  const matched = fleetRoutes.some(candidate => candidate.id.toLowerCase() === routeId.toLowerCase())

  return (
    <div class="fleet-dashboard">
      <div class="page-heading"><div><p class="eyebrow">Fleet management / route detail</p><h1>{route.id}</h1><p class="header-copy">{route.origin} to {route.destination} Â· {route.customer}</p></div><div class="header-actions"><a class="button button-secondary" href="/routes">â† All routes</a><a class="button button-secondary" href={`/traffic?route=${route.id}`}>Evaluate traffic</a><a class="button button-primary" href={`/deliveries/${route.id}`}>Confirm delivery</a></div></div>
      {!matched && <section class="panel detail-notice"><strong>Route not found</strong><span>Showing the nearest active route while you return to the route list.</span></section>}
      <section class="metric-grid"><article class="metric-card metric-card-accent"><span class="metric-label">Route status</span><strong class="detail-status">{route.status}</strong><span class="metric-note">Departure {route.departure}</span></article><article class="metric-card"><span class="metric-label">Progress</span><strong>{route.progress}</strong><span class="metric-note">Estimated arrival {route.eta}</span></article><article class="metric-card"><span class="metric-label">Vehicle temperature</span><strong>{route.temperature}</strong><span class="metric-note metric-positive">Within cold-chain range</span></article><article class="metric-card"><span class="metric-label">Assigned driver</span><strong class="detail-name">{route.driver}</strong><span class="metric-note">Vehicle {route.vehicle}</span></article></section>
      <div class="detail-grid"><section class="panel detail-panel"><div class="panel-heading"><div><p class="eyebrow">Live route activity</p><h2>Delivery timeline</h2></div><span class="pill pill-green">Live</span></div><div class="timeline"><div><span class="timeline-dot done"></span><strong>Route allocated</strong><small>08:40 Â· Fleet manager assigned {route.driver}</small></div><div><span class="timeline-dot done"></span><strong>Vehicle checked</strong><small>09:00 Â· {route.vehicle} fridge confirmed at {route.temperature}</small></div><div><span class="timeline-dot active"></span><strong>{route.status}</strong><small>Current position updates are received from the driver</small></div><div><span class="timeline-dot"></span><strong>Delivery due</strong><small>Estimated arrival {route.eta}</small></div></div></section><section class="panel detail-panel"><div class="panel-heading"><div><p class="eyebrow">Route controls</p><h2>Operations</h2></div></div><div class="detail-actions"><a class="button button-secondary" href={`/traffic?route=${route.id}`}>Check traffic conditions</a><a class="button button-secondary" href="/alerts">View route alerts</a><a class="button button-secondary" href={`/vehicles/${route.vehicle}`}>Open vehicle</a></div></section></div>
    </div>
  )
}

export const VehiclesPage = ({ vehicles = [] }: { vehicles?: any[] } = {}) => (
  <div class="fleet-dashboard">
    <div class="page-heading"><div><p class="eyebrow">Fleet management</p><h1>Vehicles</h1><p class="header-copy">Check vehicle readiness and keep every temperature-controlled load within range.</p></div><a class="button button-primary" href="/vehicles/new">+ Register vehicle</a></div>
    <section class="metric-grid"><article class="metric-card metric-card-accent"><span class="metric-label">Vehicles online</span><strong>31 <small>/ 34</small></strong><span class="metric-note metric-positive">91% availability</span></article><article class="metric-card"><span class="metric-label">Within temperature</span><strong>29</strong><span class="metric-note">94% of online vehicles</span></article><article class="metric-card"><span class="metric-label">Service due</span><strong>03</strong><span class="metric-note metric-negative">Within 500 miles</span></article><article class="metric-card"><span class="metric-label">Available now</span><strong>07</strong><span class="metric-note">Ready for allocation</span></article></section>
    <section class="panel table-panel"><div class="panel-heading"><div><h2>Vehicle readiness</h2><p class="table-caption">Live readings from registered transport</p></div><a class="text-link" href="/temperature">Open temperature monitor <span>â†’</span></a></div><div class="fleet-table-wrap"><table class="fleet-table"><thead><tr><th>Vehicle</th><th>Assigned driver</th><th>Temperature</th><th>Current status</th><th>Mileage</th><th></th></tr></thead><tbody>{vehicles.length ? vehicles.map(vehicle => { const tempAlert = vehicle.current_temperature && (vehicle.current_temperature < (vehicle.target_temperature_min || 2) || vehicle.current_temperature > (vehicle.target_temperature_max || 8)); const statusClass = vehicle.status === 'in_transit' ? 'pill-green' : vehicle.status === 'parked' ? 'pill-red' : 'pill-neutral'; return <tr><td><a href={`/vehicles/${vehicle.vehicle_reference}`} class="table-id">{vehicle.vehicle_reference}</a><span>{vehicle.vehicle_type}</span></td><td>{vehicle.driver_name || 'Unassigned'}</td><td><strong class={tempAlert ? 'text-alert' : 'text-good'}>{vehicle.current_temperature ? `${vehicle.current_temperature} C` : 'N/A'}</strong><span>{tempAlert ? 'Temperature alert' : 'Within range'}</span></td><td><span class={`pill ${statusClass}`}>{vehicle.status || 'available'}</span></td><td>{vehicle.mileage ? `${Number(vehicle.mileage).toLocaleString()} mi` : '0 mi'}</td><td><a class="table-action" href={`/vehicles/${vehicle.vehicle_reference}/edit`}>Edit</a></td></tr>; }) : <tr><td colspan="6">No vehicles registered.</td></tr>}</tbody></table></div></section>
  </div>
)

export const TemperaturePage = () => (
  <div class="fleet-dashboard temperature-page" data-temperature-page>
    <div class="page-heading"><div><p class="eyebrow">Cold-chain monitoring</p><h1>Temperature monitor</h1><p class="header-copy">Live refrigerator readings for every temperature-controlled vehicle.</p></div><div class="header-actions"><span class="sync-status"><span class="status-dot status-dot-live"></span><span data-temperature-updated>Live monitor ready</span></span><button class="button button-primary" type="button" data-temperature-refresh>Refresh readings</button></div></div>
    <section class="metric-grid"><article class="metric-card metric-card-accent"><span class="metric-label">Vehicles within range</span><strong data-temperature-within>--</strong><span class="metric-note">Target range 2 C to 8 C</span></article><article class="metric-card"><span class="metric-label">Temperature alerts</span><strong class="metric-alert" data-temperature-alerts>--</strong><span class="metric-note metric-negative">Requires attention</span></article><article class="metric-card"><span class="metric-label">Average temperature</span><strong data-temperature-average>--</strong><span class="metric-note">Across monitored vehicles</span></article><article class="metric-card"><span class="metric-label">Sensors online</span><strong data-temperature-online>--</strong><span class="metric-note metric-positive">Live sensor connection</span></article></section>
    <section class="panel table-panel"><div class="panel-heading"><div><p class="eyebrow">Live readings</p><h2>Vehicle temperature status</h2><p class="table-caption">Readings refresh automatically every 10 minutes.</p></div><a class="text-link" href="/alerts/temperature">View temperature alerts <span>â†’</span></a></div><div class="fleet-table-wrap"><table class="fleet-table"><thead><tr><th>Vehicle</th><th>Assigned driver</th><th>Current temperature</th><th>Target range</th><th>Sensor</th><th>Status</th></tr></thead><tbody data-temperature-rows><tr><td colspan="6" class="table-loading">Loading live readings...</td></tr></tbody></table></div></section>
  </div>
)

export const AlertsPage = () => (
  <div class="fleet-dashboard"><div class="page-heading"><div><p class="eyebrow">Fleet management</p><h1>Alerts</h1><p class="header-copy">Resolve temperature, traffic, route, and vehicle issues before they affect a delivery.</p></div><div class="header-actions"><span class="sync-status"><span class="status-dot status-dot-live"></span>Last updated <span data-current-time>--:--</span></span><a class="button button-secondary" href="/temperature">Temperature monitor</a><a class="button button-primary" href="/traffic">Traffic manager</a></div></div><div class="alert-page-grid"><section class="panel alert-feed"><div class="panel-heading"><div><h2>Active alerts</h2><p class="table-caption">4 issues need an operational response</p></div></div><a class="alert-item alert-critical" href="/vehicles/SN-19"><span class="alert-icon">!</span><span><strong>Temperature rising</strong><small>SN-19 Â· 8.7 C Â· 4 min ago Â· 0.7 C above maximum</small></span><span class="alert-arrow">â†’</span></a><a class="alert-item alert-warning" href="/routes/SN-204"><span class="alert-icon">!</span><span><strong>Traffic disruption</strong><small>M62 eastbound Â· SN-204 Â· compare alternative route</small></span><span class="alert-arrow">â†’</span></a><a class="alert-item" href="/vehicles"><span class="alert-icon">i</span><span><strong>Vehicle service due</strong><small>SN-11 Â· service due in 120 miles Â· schedule inspection</small></span><span class="alert-arrow">â†’</span></a><a class="alert-item" href="/routes"><span class="alert-icon">i</span><span><strong>Route awaiting driver</strong><small>SN-207 Â· no accepted allocation Â· delivery at risk</small></span><span class="alert-arrow">â†’</span></a></section><section class="panel alert-guide"><p class="eyebrow">Response guide</p><h2>What each issue means</h2><div class="alert-explanations"><div><strong>Temperature</strong><span>Protect the load, check the refrigeration unit and hold delivery until readings return to range.</span></div><div><strong>Traffic</strong><span>Evaluate the route, confirm the delay and approve the safest available alternative.</span></div><div><strong>Service</strong><span>Book maintenance before the vehicle exceeds its service interval.</span></div><div><strong>Driver allocation</strong><span>Assign and confirm a driver before the scheduled departure window.</span></div></div><a class="button button-secondary" href="/monitoring">Open monitoring</a></section></div></div>
)

export const MonitoringPage = () => (
  <div class="fleet-dashboard"><div class="page-heading"><div><p class="eyebrow">Performance intelligence</p><h1>Monitoring</h1><p class="header-copy">Track the measures that keep Snow Logistics reliable, safe, and on time.</p></div><div class="header-actions"><span class="sync-status"><span class="status-dot status-dot-live"></span>Live data Â· 10:42</span><a class="button button-secondary" href="/monitoring/export">Export report</a></div></div><section class="metric-grid"><article class="metric-card metric-card-accent"><span class="metric-label">On-time delivery</span><strong>96.4%</strong><span class="metric-note metric-positive">+1.8% this week</span></article><article class="metric-card"><span class="metric-label">Average route time</span><strong>3h 42m</strong><span class="metric-note metric-positive">12 min faster</span></article><article class="metric-card"><span class="metric-label">Temperature compliance</span><strong>98.7%</strong><span class="metric-note">29 of 31 vehicles</span></article><article class="metric-card"><span class="metric-label">Driver acceptance</span><strong>89%</strong><span class="metric-note">Last 30 days</span></article></section><div class="monitor-grid"><section class="panel chart-panel"><div class="panel-heading"><div><p class="eyebrow">Delivery performance</p><h2>On-time delivery trend</h2></div><span class="chart-period">Last 7 days</span></div><div class="bar-chart">{[78, 84, 81, 91, 88, 96, 96].map((value, index) => <div class="chart-column"><span style={`height: ${value}%`}></span><small>{['Wed', 'Thu', 'Fri', 'Sat', 'Sun', 'Mon', 'Tue'][index]}</small></div>)}</div></section><section class="panel chart-panel"><div class="panel-heading"><div><p class="eyebrow">Cold chain</p><h2>Temperature compliance</h2></div><span class="chart-period">This week</span></div><div class="donut-metric"><div class="donut"><strong>98.7%</strong><small>compliant</small></div><div class="legend"><span><i class="legend-good"></i>Within range <b>29</b></span><span><i class="legend-alert"></i>Needs attention <b>2</b></span></div></div></section></div></div>
)

const fallbackDrivers = [
  { reference: 'DRV-018', name: 'Amelia Carter', phone: '+44 7700 900 118', route: 'SN-204', status: 'On route', acceptance: '98%' },
  { reference: 'DRV-021', name: 'Marcus Green', phone: '+44 7700 900 121', route: 'SN-205', status: 'Loading', acceptance: '94%' },
  { reference: 'DRV-025', name: 'Nia Patel', phone: '+44 7700 900 125', route: 'SN-206', status: 'On route', acceptance: '91%' },
  { reference: 'DRV-030', name: 'Owen Hughes', phone: '+44 7700 900 130', route: 'SN-207', status: 'Available', acceptance: '87%' },
]

export const DriversPage = ({ drivers = fallbackDrivers, currentUser }: { drivers?: any[]; currentUser?: any } = {}) => {
  const normalizedRole = String(currentUser?.role || '').trim().toLowerCase().replace(/\s+/g, '_')
  const isAdmin = ['admin', 'fleet_manager'].includes(normalizedRole)
  return (
  <div class="fleet-dashboard"><div class="page-heading"><div><p class="eyebrow">Fleet management</p><h1>Drivers</h1><p class="header-copy">See who is available, assigned, and servicing each route.</p></div><div class="header-actions"><a class="button button-secondary" href="/admin/drivers" data-admin-only hidden>All registered drivers</a><a class="button button-primary" href="/drivers/new">+ Register driver</a></div></div><section class="metric-grid"><article class="metric-card metric-card-accent"><span class="metric-label">Active drivers</span><strong>{drivers.length}</strong><span class="metric-note">Registered driver records</span></article><article class="metric-card"><span class="metric-label">Available</span><strong>{drivers.filter(driver => ['available', 'Available'].includes(driver.status)).length.toString().padStart(2, '0')}</strong><span class="metric-note metric-positive">Ready for allocation</span></article><article class="metric-card"><span class="metric-label">Licence checks due</span><strong>--</strong><span class="metric-note metric-negative">Review registered records</span></article><article class="metric-card"><span class="metric-label">Assigned routes</span><strong>{drivers.filter(driver => driver.route_reference || driver.route).length}</strong><span class="metric-note">Current allocations</span></article></section><section class="panel table-panel"><div class="panel-heading"><div><h2>Driver roster</h2><p class="table-caption">Current assignments and service readiness</p></div><a class="text-link" href="/routes">View route allocations <span>â†’</span></a></div><div class="fleet-table-wrap"><table class="fleet-table"><thead><tr><th>Driver</th><th>Contact</th><th>Assigned route</th><th>Licence expiry</th><th>Status</th><th></th></tr></thead><tbody>{drivers.length ? drivers.map(driver => { const reference = driver.driver_reference || driver.reference; const name = driver.full_name || driver.name || reference; const route = driver.route_reference || driver.route || 'Unassigned'; const status = driver.status || 'available'; return <tr><td><a href={`/drivers/${reference}`} class="table-id">{name}</a><span>{reference}</span></td><td>{driver.email || driver.phone || 'No contact recorded'}{driver.email && <span>{driver.phone || 'No phone recorded'}</span>}</td><td>{route}<span>{driver.origin && driver.destination ? `${driver.origin} to ${driver.destination}` : 'No active route'}</span></td><td>{driver.licence_expiry || 'Not recorded'}</td><td><span class={`pill ${['assigned', 'On route', 'in_transit'].includes(status) ? 'pill-green' : ['loading', 'Loading'].includes(status) ? 'pill-amber' : 'pill-neutral'}`}>{status}</span></td><td><a class="table-action" href={`/drivers/${reference}/edit`} style={isAdmin ? {} : { display: 'none' }}>Edit</a></td></tr>}) : <tr><td colspan="6">No registered drivers found.</td></tr>}</tbody></table></div></section></div>
  )
}

export const AdminDriversPage = ({ drivers = [] }: { drivers?: any[] } = {}) => (
  <div class="fleet-dashboard"><div class="page-heading"><div><p class="eyebrow">Admin / driver management</p><h1>All registered drivers</h1><p class="header-copy">Review every registered driver account, licence record, and current status.</p></div><a class="button button-secondary" href="/drivers">← Drivers</a></div><section class="panel table-panel"><div class="panel-heading"><div><h2>Registered driver directory</h2><p class="table-caption">Admin-only operational records</p></div><span class="pill pill-green">Admin access</span></div><div class="fleet-table-wrap"><table class="fleet-table"><thead><tr><th>Driver</th><th>Contact</th><th>Licence</th><th>Licence expiry</th><th>Status</th><th></th></tr></thead><tbody>{drivers.length ? drivers.map(driver => <tr><td><a class="table-id" href={`/drivers/${driver.driver_reference}`}>{driver.full_name}</a><span>{driver.driver_reference}</span></td><td>{driver.email}<span>{driver.phone || 'No phone recorded'}</span></td><td>{driver.licence_number}</td><td>{driver.licence_expiry}</td><td><span class="pill pill-green">{driver.status || 'active'}</span></td><td><a class="table-action" href={`/drivers/${driver.driver_reference}/edit`}>Edit</a></td></tr>) : <tr><td colspan="6">No registered drivers found.</td></tr>}</tbody></table></div></section></div>
)

const customers = [
  { reference: 'CUS-0041', name: 'Northstar Medical', contact: 'operations@northstar.example', routes: '12', lastRoute: 'SN-204', status: 'Active' },
  { reference: 'CUS-0046', name: 'Carewell Clinics', contact: 'dispatch@carewell.example', routes: '08', lastRoute: 'SN-205', status: 'Active' },
  { reference: 'CUS-0053', name: 'MedEquip UK', contact: 'logistics@medequip.example', routes: '06', lastRoute: 'SN-206', status: 'Active' },
  { reference: 'CUS-0060', name: 'Wellbeing Direct', contact: 'transport@wellbeing.example', routes: '03', lastRoute: 'SN-207', status: 'Pending review' },
  { reference: 'PRO-0101', name: 'Bidfood Liverpool', contact: 'LiverpoolCustomerService@bidfood.co.uk', routes: 'â€”', lastRoute: 'Prospect', status: 'Prospect' },
  { reference: 'PRO-0102', name: 'Bidfood Manchester', contact: 'manchestercustomerservice@bidfood.co.uk', routes: 'â€”', lastRoute: 'Prospect', status: 'Prospect' },
  { reference: 'PRO-0103', name: 'Best Food Logistics', contact: '0161 627 0050', routes: 'â€”', lastRoute: 'Prospect', status: 'Prospect' },
  { reference: 'PRO-0104', name: 'NHS Supply Chain', contact: 'Website enquiry form', routes: 'â€”', lastRoute: 'Prospect', status: 'Prospect' },
  { reference: 'PRO-0105', name: 'Brakes Warrington', contact: 'Central switchboard via Brakes', routes: 'â€”', lastRoute: 'Prospect', status: 'Prospect' },
  { reference: 'PRO-0106', name: 'Peter Green Chilled', contact: 'sales@petergreenchilled.co.uk', routes: 'â€”', lastRoute: 'Prospect', status: 'Prospect' },
  { reference: 'PRO-0107', name: 'Americold UK', contact: 'Website contact form', routes: 'â€”', lastRoute: 'Prospect', status: 'Prospect' },
  { reference: 'PRO-0108', name: 'Lineage Logistics UK', contact: 'Website contact form', routes: 'â€”', lastRoute: 'Prospect', status: 'Prospect' },
  { reference: 'PRO-0109', name: 'Culina Group', contact: 'Website contact form', routes: 'â€”', lastRoute: 'Prospect', status: 'Prospect' },
  { reference: 'PRO-0110', name: 'Reed Boardall', contact: 'Website contact form', routes: 'â€”', lastRoute: 'Prospect', status: 'Prospect' },
  { reference: 'PRO-0111', name: 'NewCold', contact: 'Website contact form', routes: 'â€”', lastRoute: 'Prospect', status: 'Prospect' },
  { reference: 'PRO-0112', name: 'DFDS Logistics', contact: 'Website contact form', routes: 'â€”', lastRoute: 'Prospect', status: 'Prospect' },
  { reference: 'PRO-0113', name: 'Fowler Welch', contact: 'Website contact form', routes: 'â€”', lastRoute: 'Prospect', status: 'Prospect' },
  { reference: 'PRO-0114', name: 'Fresh Direct', contact: 'Website contact form', routes: 'â€”', lastRoute: 'Prospect', status: 'Prospect' },
  { reference: 'PRO-0115', name: 'Booker Wholesale', contact: 'Website contact form', routes: 'â€”', lastRoute: 'Prospect', status: 'Prospect' },
  { reference: 'PRO-0116', name: 'Health Procurement Portal', contact: 'Supplier registration portal', routes: 'â€”', lastRoute: 'Prospect', status: 'Prospect' },
  { reference: 'PRO-0117', name: 'NHS England Supplier Team', contact: 'england.supplier@nhs.net', routes: 'â€”', lastRoute: 'Prospect', status: 'Prospect' },
  { reference: 'PRO-0118', name: 'NHS Supply Chain Food', contact: 'Food category enquiry form', routes: 'â€”', lastRoute: 'Prospect', status: 'Prospect' },
  { reference: 'PRO-0119', name: 'Country Valley Foods', contact: 'info@countryvalley.co.uk / 01642 562360', routes: 'â€”', lastRoute: 'Prospect', status: 'Prospect' },
  { reference: 'PRO-0120', name: 'Lowrie Foods', contact: 'orders@lowriefoods.co.uk / 0191 265 9161', routes: 'â€”', lastRoute: 'Prospect', status: 'Prospect' },
  { reference: 'PRO-0121', name: 'Bidfood Newcastle', contact: '0370 3663 450', routes: 'â€”', lastRoute: 'Prospect', status: 'Prospect' },
  { reference: 'PRO-0122', name: 'Reynolds Food Group', contact: 'Contact via website', routes: 'â€”', lastRoute: 'Prospect', status: 'Prospect' },
  { reference: 'PRO-0123', name: 'JR Holland', contact: 'Contact via website', routes: 'â€”', lastRoute: 'Prospect', status: 'Prospect' },
]

export const CustomersPage = ({ currentUser }: { currentUser?: any } = {}) => {
  const normalizedRole = String(currentUser?.role || '').trim().toLowerCase().replace(/\s+/g, '_')
  const isAdmin = ['admin', 'fleet_manager'].includes(normalizedRole)
  return (
  <div class="fleet-dashboard"><div class="page-heading"><div><p class="eyebrow">Fleet management</p><h1>Customers</h1><p class="header-copy">Manage affiliated customers, their delivery requirements, and route history.</p></div>{isAdmin && <a class="button button-primary" href="/customers/new">+ Register customer</a>}</div><section class="metric-grid"><article class="metric-card metric-card-accent"><span class="metric-label">Active customers</span><strong>42</strong><span class="metric-note metric-positive">+4 this month</span></article><article class="metric-card"><span class="metric-label">Routes this month</span><strong>186</strong><span class="metric-note">Across all customers</span></article><article class="metric-card"><span class="metric-label">Service requests</span><strong>09</strong><span class="metric-note">Awaiting review</span></article><article class="metric-card"><span class="metric-label">Customer satisfaction</span><strong>4.8 <small>/ 5</small></strong><span class="metric-note metric-positive">Based on 118 deliveries</span></article></section><section class="panel table-panel"><div class="panel-heading"><div><h2>Customer directory</h2><p class="table-caption">Affiliated customers and route prospects from the customer prospectus</p></div><a class="text-link" href="/routes/scan">Scan for routes <span>â†’</span></a></div><div class="fleet-table-wrap"><table class="fleet-table"><thead><tr><th>Customer</th><th>Contact</th><th>Routes</th><th>Last route</th><th>Status</th><th></th></tr></thead><tbody>{customers.map(customer => <tr><td><a href={`/customers/${customer.reference}`} class="table-id">{customer.name}</a><span>{customer.reference}</span></td><td>{customer.contact}</td><td>{customer.routes}</td><td>{customer.lastRoute}</td><td><span class={`pill ${customer.status === 'Active' ? 'pill-green' : customer.status === 'Prospect' ? 'pill-neutral' : 'pill-amber'}`}>{customer.status}</span></td><td>{isAdmin && <a class="table-action" href={`/customers/${customer.reference}/edit`}>Edit</a>}</td></tr>)}</tbody></table></div></section></div>
  )
}

export const RouteScanPage = () => (
  <div class="fleet-dashboard">
    <div class="page-heading"><div><p class="eyebrow">Route intelligence</p><h1>Route scanning</h1><p class="header-copy">Find upcoming deliveries from affiliated customers and load suitable work into the portal.</p></div><span class="sync-status"><span class="status-dot status-dot-live"></span><span data-route-scan-live>Scanner ready</span></span></div>
    <div class="scan-layout">
      <section class="panel scan-control-panel"><div class="panel-heading"><div><p class="eyebrow">UK cold-chain network scan</p><h2>Discover upcoming routes</h2></div><span class="scan-pulse" data-route-scan-pulse></span></div><form data-route-scan-form class="scan-form"><label>Scan sources<select name="source"><option value="all">All cold-chain sources</option><option value="customers">Affiliated customers</option><option value="market">Cold-chain market</option></select></label><label>Priority region<select name="region"><option value="north_west">North West England</option><option value="all_uk">All United Kingdom</option></select></label><label>Look ahead<select name="window"><option value="7">Next 7 days</option><option value="14">Next 14 days</option><option value="30">Next 30 days</option></select></label><button class="button button-primary" type="submit" data-route-scan-button>Scan now</button></form><p class="scan-helper">The scanner checks UK cold-chain logistics companies and affiliated customer requests, prioritising North West England before widening across the United Kingdom. Results refresh automatically every 10 minutes.</p></section>
      <section class="panel scan-summary-panel"><p class="eyebrow">Last scan</p><strong data-route-scan-count>Ready</strong><span data-route-scan-time>Run a scan to load the latest route candidates.</span><div class="scan-summary-line"><span><i class="legend-good"></i>UK cold-chain companies</span><b>18</b></div><div class="scan-summary-line"><span><i class="legend-good"></i>North West priority matches</span><b data-route-scan-priority>--</b></div></section>
    </div>
    <section class="panel scan-results-panel"><div class="panel-heading"><div><p class="eyebrow">Candidate routes</p><h2>Upcoming availability</h2></div><span class="table-caption" data-route-scan-result-label>No scan run yet</span></div><div data-route-scan-results class="scan-results-empty"><strong>Start a scan to discover upcoming routes.</strong><span>New route opportunities will appear here for review and allocation.</span></div></section>
  </div>
)

export const TrafficPage = () => (
  <div class="fleet-dashboard">
    <div class="page-heading"><div><p class="eyebrow">Route traffic management</p><h1>Traffic manager</h1><p class="header-copy">Compare live traffic from Waze and Google Maps before disruption reaches the driver.</p></div><span class="sync-status"><span class="status-dot status-dot-live"></span><span data-traffic-live>Traffic monitor ready</span></span></div>
    <div class="traffic-layout">
      <section class="panel traffic-control-panel"><div class="panel-heading"><div><p class="eyebrow">Live route evaluation</p><h2>Check route conditions</h2></div><span class="scan-pulse" data-traffic-pulse></span></div><form data-traffic-form class="traffic-form"><label>Route<select name="route"><option value="SN-204">SN-204 Â· Manchester to Leeds</option><option value="SN-205">SN-205 Â· Liverpool to Sheffield</option><option value="SN-206">SN-206 Â· Birmingham to Nottingham</option></select></label><button class="button button-primary" type="submit" data-traffic-button>Scan traffic</button></form><p class="scan-helper">Both providers are evaluated for delays, incidents, closures, and route alternatives. The recommendation prioritises the fastest safe route. Traffic refreshes automatically every 10 minutes.</p></section>
      <section class="panel provider-status-panel"><p class="eyebrow">Provider health</p><h2>Traffic sources</h2><div class="provider-status"><span><i class="legend-good"></i>Waze traffic</span><b data-traffic-waze>Ready</b></div><div class="provider-status"><span><i class="legend-good"></i>Google Maps</span><b data-traffic-google>Ready</b></div><small>Provider credentials can be configured through Cloudflare secrets.</small></section>
    </div>
    <section class="panel traffic-results-panel"><div class="panel-heading"><div><p class="eyebrow">Route evaluation</p><h2 data-traffic-route>Choose a route to scan</h2></div><span class="table-caption" data-traffic-label>No scan run yet</span></div><div data-traffic-results class="traffic-results-empty"><strong>Scan a route to compare live conditions.</strong><span>Disruptions and alternatives will appear here.</span></div></section>
  </div>
)
