const inputStyle = 'width: 100%; min-height: 42px; padding: 0 11px; border: 1px solid #dfe6e8; background: white; color: #18232b; font-family: inherit; font-size: 12px;'
const labelStyle = 'display: grid; gap: 7px; color: #73808a; font-size: 10px; font-weight: 700; letter-spacing: .5px; text-transform: uppercase;'

const FleetForm = ({ action, title, description, backHref, children }: { action: string; title: string; description: string; backHref: string; children: any }) => (
  <div class="fleet-dashboard"><div class="page-heading"><div><p class="eyebrow">Fleet management</p><h1>{title}</h1><p class="header-copy">{description}</p></div><a class="button button-secondary" href={backHref}>← Back</a></div><section class="panel form-panel"><form method="post" action={action} class="fleet-form">{children}<div class="form-actions"><a class="button button-secondary" href={backHref}>Cancel</a><button class="button button-primary" type="submit">Save record</button></div></form></section></div>
)

export const RouteFormPage = () => <FleetForm action="/api/fleet/routes" title="Allocate route" description="Create a delivery route and assign it to a driver and vehicle." backHref="/routes"><div class="form-grid"><label style={labelStyle}>Route reference<input style={inputStyle} name="route_reference" required placeholder="SN-208" /></label><label style={labelStyle}>Customer ID<input style={inputStyle} name="customer_id" type="number" /></label><label style={labelStyle}>Origin<input style={inputStyle} name="origin" required placeholder="Liverpool" /></label><label style={labelStyle}>Destination<input style={inputStyle} name="destination" required placeholder="Manchester" /></label><label style={labelStyle}>Driver ID<input style={inputStyle} name="driver_id" type="number" /></label><label style={labelStyle}>Vehicle ID<input style={inputStyle} name="vehicle_id" type="number" /></label><label style={labelStyle}>Scheduled departure<input style={inputStyle} name="scheduled_departure" type="datetime-local" required /></label><label style={labelStyle}>Estimated arrival<input style={inputStyle} name="estimated_arrival" type="datetime-local" /></label><label style={labelStyle}>Cargo description<input style={inputStyle} name="cargo_description" placeholder="Temperature-controlled medicines" /></label><label style={labelStyle}>Traffic status<select style={inputStyle} name="traffic_status"><option value="clear">Clear</option><option value="slow">Slow</option><option value="disrupted">Disrupted</option></select></label></div></FleetForm>

export const VehicleFormPage = () => <FleetForm action="/api/fleet/vehicles" title="Register vehicle" description="Add a transport record and configure its cold-chain temperature range." backHref="/vehicles"><div class="form-grid"><label style={labelStyle}>Vehicle reference<input style={inputStyle} name="vehicle_reference" required placeholder="SN-24" /></label><label style={labelStyle}>Registration number<input style={inputStyle} name="registration_number" required placeholder="SN24 ABC" /></label><label style={labelStyle}>Vehicle type<input style={inputStyle} name="vehicle_type" required placeholder="Refrigerated van" /></label><label style={labelStyle}>Make<input style={inputStyle} name="make" /></label><label style={labelStyle}>Model<input style={inputStyle} name="model" /></label><label style={labelStyle}>Year<input style={inputStyle} name="year" type="number" /></label><label style={labelStyle}>Temperature controlled<select style={inputStyle} name="temperature_controlled"><option value="1">Yes</option><option value="0">No</option></select></label><label style={labelStyle}>Minimum temperature C<input style={inputStyle} name="target_temperature_min" type="number" step="0.1" value="2" /></label><label style={labelStyle}>Maximum temperature C<input style={inputStyle} name="target_temperature_max" type="number" step="0.1" value="8" /></label><label style={labelStyle}>Mileage<input style={inputStyle} name="mileage" type="number" min="0" value="0" /></label><label style={labelStyle}>Last service date<input style={inputStyle} name="last_service_date" type="date" /></label></div></FleetForm>

export const VehicleEditPage = ({ vehicle }: { vehicle: any }) => <FleetForm action={`/api/fleet/vehicles/${encodeURIComponent(vehicle.vehicle_reference)}`} title={`Edit vehicle ${vehicle.vehicle_reference}`} description="Update transport details, readiness, and cold-chain operating limits." backHref="/vehicles"><div class="form-grid"><label style={labelStyle}>Vehicle reference<input style={inputStyle} name="vehicle_reference" value={String(vehicle.vehicle_reference || '')} required /></label><label style={labelStyle}>Registration number<input style={inputStyle} name="registration_number" value={String(vehicle.registration_number || '')} required /></label><label style={labelStyle}>Vehicle type<input style={inputStyle} name="vehicle_type" value={String(vehicle.vehicle_type || '')} required /></label><label style={labelStyle}>Make<input style={inputStyle} name="make" value={String(vehicle.make || '')} /></label><label style={labelStyle}>Model<input style={inputStyle} name="model" value={String(vehicle.model || '')} /></label><label style={labelStyle}>Year<input style={inputStyle} name="year" type="number" value={String(vehicle.year || '')} /></label><label style={labelStyle}>Status<select style={inputStyle} name="status" value={String(vehicle.status || 'available')}><option value="available">Available</option><option value="assigned">Assigned</option><option value="in_transit">In transit</option><option value="loading">Loading</option><option value="parked">Parked</option><option value="maintenance">Maintenance</option><option value="offline">Offline</option></select></label><label style={labelStyle}>Temperature controlled<select style={inputStyle} name="temperature_controlled" value={String(vehicle.temperature_controlled ?? 1)}><option value="1">Yes</option><option value="0">No</option></select></label><label style={labelStyle}>Minimum temperature C<input style={inputStyle} name="target_temperature_min" type="number" step="0.1" value={String(vehicle.target_temperature_min ?? '')} /></label><label style={labelStyle}>Maximum temperature C<input style={inputStyle} name="target_temperature_max" type="number" step="0.1" value={String(vehicle.target_temperature_max ?? '')} /></label><label style={labelStyle}>Mileage<input style={inputStyle} name="mileage" type="number" min="0" value={String(vehicle.mileage || 0)} /></label><label style={labelStyle}>Last service date<input style={inputStyle} name="last_service_date" type="date" value={String(vehicle.last_service_date || '')} /></label></div></FleetForm>

export const DriverFormPage = () => <FleetForm action="/api/fleet/drivers" title="Register driver" description="Add a driver and complete licence and availability checks." backHref="/drivers"><div class="form-grid"><label style={labelStyle}>Driver reference<input style={inputStyle} name="driver_reference" required placeholder="DRV-031" /></label><label style={labelStyle}>Full name<input style={inputStyle} name="full_name" required /></label><label style={labelStyle}>Email<input style={inputStyle} name="email" type="email" /></label><label style={labelStyle}>Phone<input style={inputStyle} name="phone" /></label><label style={labelStyle}>Licence number<input style={inputStyle} name="licence_number" required /></label><label style={labelStyle}>Licence expiry<input style={inputStyle} name="licence_expiry" type="date" required /></label><label style={labelStyle}>Emergency contact<input style={inputStyle} name="emergency_contact_name" /></label><label style={labelStyle}>Emergency phone<input style={inputStyle} name="emergency_contact_phone" /></label></div></FleetForm>

export const CustomerFormPage = () => <FleetForm action="/api/fleet/customers" title="Register customer" description="Add an affiliated customer and their delivery contact details." backHref="/customers"><div class="form-grid"><label style={labelStyle}>Organisation name<input style={inputStyle} name="full_name" required /></label><label style={labelStyle}>Email<input style={inputStyle} name="email" type="email" required /></label><label style={labelStyle}>Phone<input style={inputStyle} name="phone" /></label><label style={labelStyle}>Postcode<input style={inputStyle} name="postcode" /></label><label style={labelStyle}>Delivery requirements<textarea style={`${inputStyle}; min-height: 100px; padding-top: 10px;`} name="delivery_requirements"></textarea></label><label style={labelStyle}>Temporary password<input style={inputStyle} name="password" type="password" required /></label></div></FleetForm>

export const ManagementPage = ({ title, eyebrow = 'Fleet management', identifier, message, backHref = '/' }: { title: string; eyebrow?: string; identifier?: string; message: string; backHref?: string }) => <div class="fleet-dashboard"><div class="page-heading"><div><p class="eyebrow">{eyebrow}</p><h1>{title}</h1><p class="header-copy">{message}</p></div><a class="button button-secondary" href={backHref}>← Back</a></div><section class="panel detail-panel"><div class="panel-heading"><div><p class="eyebrow">Record {identifier || 'new'}</p><h2>{identifier ? 'Record overview' : 'Create record'}</h2></div><span class="pill pill-neutral">Ready</span></div><div class="management-placeholder"><strong>{identifier ? 'This record is ready for operational updates.' : 'This workflow is ready for a new record.'}</strong><span>Use the list page controls to create and manage operational data.</span></div></section></div>

export const MonitoringExportPage = () => (
  <ManagementPage title="Monitoring export" eyebrow="Performance intelligence" message="Prepare a monitoring report for routes, deliveries, drivers, and temperature compliance." backHref="/monitoring" />
)
